#!/bin/bash

# exit from any errors
set -e

# Create our config that does not reside in the package
echo "/var/log/toplogger  # Directory where logs are sorted and kept" > "/etc/toplogger/logdir"

# Make the loop script executable
chmod +x /usr/lib/toplogger/toplogger.sh

# Service
systemctl daemon-reload
systemctl enable toplogger
systemctl start toplogger

# AppArmor
apparmor_parser -r /etc/apparmor.d/usr.lib.toplogger.toplogger.sh
aa-enforce /etc/apparmor.d/usr.lib.toplogger.toplogger.sh